### PR TITLE
Fix double serialization

### PR DESCRIPTION
**Pull request by tarrencev**
The response payload was being serialized twice, once by plasma-core and again by express here. With this modification, the node will forward the raw handler response.

### CODE REVIEW

**Comment by tarrencev** [comment]
Hmm if we do this we might have to manually set the content type response headers

**Comment by tarrencev** [comment]
The issue I'm seeing right now is that the response is getting stringify'd twice and I'm seeing responses like 

```json
"{\"jsonrpc\":\"2.0\",\"result\":{},\"id\":\"0\"}"
```

I think `response.json` expects an object, and is calling `JSON.stringify` on it internally as well.

I was thinking we could stop encoding the json here but perhaps there is a better fix

**Comment by kfichter** [comment]
Maybe better to just stop returning stringified results from plasma-core.

**Comment by tarrencev** [comment]
Sounds good! I'll submit a PR with the change there.

**Pull request closed without merging**
